//mine
export const POSTS_ARE_LOADING = 'POSTS_ARE_LOADING';
export const POSTS_LOAD_ERROR = 'POSTS_LOAD_ERROR';








//Auth
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';



//POst crud

export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const POST_SUBMITTED = 'POST_SUBMITTED';
export const DELETE_POST = 'DELETE_POST';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const POST_PAGE_LOADED = 'POST_PAGE_LOADED';
export const POST_PAGE_UNLOADED = 'POST_PAGE_UNLOADED';
export const POST_LIKED = 'POST_LIKED';
export const POST_UNLIKED = 'POST_UNLIKED';
export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER';
export const CHANGE_TAB = 'CHANGE_TAB';
export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED';
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const LOAD_FOLLOWERS = 'LOAD_FOLLOWERS';
