import {
	REGISTER, LOGIN, LOGOUT, GET_TOKEN, SET_CURRENT_USER, SET_TOKEN, REGISTER_ERROR, LOGIN_ERROR
, REGISTER_SUCCESS, LOGIN_SUCCESS, APP_LOAD} from './actionTypes'
import agent from '../agent';


